# Copyright 2023 Samsung Electronics Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu-11" do |config|
  config.vm.hostname = "ubuntu-11"
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 20001, host: 20001
  config.vm.network "forwarded_port", guest: 30309, host: 30309
  end
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "40960", "--cpus", "20"]
  #  config.disksize.size = '120GB'
  end
    config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yaml"
    ansible.raw_arguments = ["-e os_user=vagrant -e os_group=vagrant"]
  end
end
