#!/bin/bash
################################################################################
#   Copyright (c) 2020 AT&T Intellectual Property.                             #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
################################################################################

echo "===> Starting at $(date)"

echo && echo "===> Cleaning up any previous SMO deployment"
echo "======> Deleting all Helm deployments"
helm list | sed -e 1d | cut -f1 | xargs helm delete --purge

echo "======> Clearing out all ONAP deployment resources"
kubectl delete ns onap
kubectl get pv --all-namespaces |cut -f1 -d' ' |xargs kubectl delete pv
kubectl get clusterrolebindings | grep onap | cut -f1 -d' ' |xargs kubectl delete clusterrolebindings
rm -rf /dockerdata-nfs

echo "======> Clearing out all RICAUX deployment resources"
kubectl delete ns ricaux
kubectl delete ns ricinfra
rm -rf /opt/data/dashboard-data

#echo "======> Clearing out all NONRTRIC deployment resources"
#kubectl delete ns nonrtric

echo "===> Completing at $(date)"
